nvidia:
  base_url: "https://integrate.api.nvidia.com/v1"
  api_key: "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"  # Replace with actual key
intelx:
  api_key: "2b0dbab0-4330-4990-8e54-6ee72001df9b"

leaklookup_key: "aeb67c0eb408806180951917aa38335b"
dehashed_key: "zQqWwsKDmToShamk2ihpG1hT06Y8Ve5eB/R9j1M1iYM1ohk6n6D2qZ8="
user_agent: "ASM-Tool/2.0 (+https://your.domain)"